
// TYPES DE REGISTRO DE USUARIOS
export const REGISTRO_EXITOSO = 'REGISTRO_EXITOSO'
export const REGISTRO_ERROR = 'REGISTRO_ERROR'

// TYPES DE LOGIN DE USUARIOS
export const LOGIN_EXITOSO = 'LOGIN_EXITOSO'
export const LOGIN_ERROR = 'LOGIN_ERROR'

// TYPES DE SESION DE USUARIOS
export const USUARIO_AUTENTICADO = 'USUARIO_AUTENTICADO'
export const CERRAR_SESION = 'CERRAR_SESION'

// TYPES DE ALERTA
export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA'
export const OCULTAR_ALERTA = 'OCULTAR_ALERTA'

// TYPES DE SUBIR ARCHIVOS
export const SUBIR_ARCHIVO = 'SUBIR_ARCHIVO'
export const SUBIR_ARCHIVO_EXITO = 'SUBIR_ARCHIVO_EXITO'
export const SUBIR_ARCHIVO_ERROR = 'SUBIR_ARCHIVO_ERROR'

// TYPES DE CREAR ENLACE
export const CREAR_ENLACE_EXITO = 'CREAR_ENLACE_EXITO'
export const CREAR_ENLACE_ERROR = 'CREAR_ENLACE_ERROR'

// TYPES PARA RESETEAR EL STATE
export const LIMPIAR_STATE = 'LIMPIAR_STATE'

// TYPES PARA GUARDAR LA CONTRASEÑA DEL ARCHIVO
export const AGREGAR_PASSWORD = 'AGREGAR_PASSWORD'

// TYPES PARA GUARDAR EL NUMERO DE DESCARGAS DEL ARCHIVO
export const AGREGAR_DESCARGAS = 'AGREGAR_DESCARGAS'